### ISSUE TITLE
Malicious Code Infection

### ISSUE THREAD

**Issue by Vampurica** [Studio-PLAYERS/TEBEX-Doc#1]
Hello,

I am opening this issue to make you aware that your repository is infected with malicious Lua code designed to backdoor servers. It does this by adding an infection line to other resources on servers that run infected resources, spreading to other servers when that code is shared. It allows the creator to modify code on those FiveM servers, modify the database, drop malware on the machine, or even add backdoor access to the machine at their command.

This code is likely here due to the FiveM server you are working on this resource in having unknowingly installed an infected resource. Many of the other resources and work from that server are also likely infected.

A direct link to the lines is found here, though many more may exist through your repos:
https://github.com/Studio-PLAYERS/TEBEX-Doc/blob/3c8857e53b1f21e136426a737cc0b52129d5bae4/SA-Money/old_player.lua#L759-L763

I would urge you to read more about this type of malicious code in the free repository provided by the creator of Phoenix Anticheat below, and to remove it from all of your resources:
https://github.com/IAmElement/fivemantivirus

If you have any questions, I will do my best to reply to this issue.

**Comment by Dragodast** [comment]
https://github.com/Studio-PLAYERS/TEBEX-Doc/commit/09b15bf5d573ba13e3e0f98123c2f58fbc8290ea
